// src/components/CircularProgress.vue
<template>
  <view class="circular-container">
    <wd-circle
      v-model="progress"
      :size="size"
      :stroke-width="strokeWidth"
      :color="isOverLimit ? '#ef4444' : '#10b981'"
      :layer-color="layerColor"
    >
      <view class="center-content">
        <text :class="['value', { 'text-red': isOverLimit }]">{{ Math.abs(remaining) }}</text>
        <text class="label">{{ isOverLimit ? '超出' : '剩余' }} kcal</text>
      </view>
    </wd-circle>
  </view>
</template>

<script setup lang="ts">
const { isDark } = useManualTheme()

const props = withDefaults(defineProps<{
  current: number
  total: number
  size?: number
  strokeWidth?: number
}>(), {
  size: 160,
  strokeWidth: 10,
})

const remaining = computed(() => props.total - props.current)
const progress = computed(() => Math.min((props.current / props.total) * 100, 100))
const isOverLimit = computed(() => remaining.value <= 0)

const layerColor = computed(() => {
  return isDark.value ? '#374151' : '#e5e7eb'
})
</script>

<style scoped>
.circular-container {
  display: flex;
  align-items: center;
  justify-content: center;
}
.center-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.value {
  font-size: 32px;
  font-weight: bold;
  color: var(--text-main);
  line-height: 1;
}
.text-red {
  color: #ef4444;
}
.label {
  font-size: 12px;
  color: var(--text-sub);
  margin-top: 4px;
}
</style>

// src/app/components/CircularProgress.tsx
interface CircularProgressProps {
  current: number;
  total: number;
  size?: number;
  strokeWidth?: number;
}

export function CircularProgress({ 
  current, 
  total, 
  size = 180, 
  strokeWidth = 12 
}: CircularProgressProps) {
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const remaining = total - current;
  const progress = Math.min((current / total) * 100, 100);
  const offset = circumference - (progress / 100) * circumference;
  
  const isOverLimit = remaining <= 0;

  return (
    <div className="relative inline-flex items-center justify-center">
      <svg width={size} height={size} className="transform -rotate-90">
        {/* 背景圆环 */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="currentColor"
          strokeWidth={strokeWidth}
          className="text-gray-200 dark:text-gray-700"
        />
        {/* 进度圆环 */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke={isOverLimit ? "#ef4444" : "#10b981"}
          strokeWidth={strokeWidth}
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
          className="transition-all duration-500"
        />
      </svg>
      {/* 中心内容 */}
      <div className="absolute flex flex-col items-center justify-center">
        <div className={`text-4xl ${isOverLimit ? 'text-red-500 dark:text-red-400' : 'text-gray-900 dark:text-gray-100'}`}>
          {Math.abs(remaining)}
        </div>
        <div className="text-sm text-gray-500 dark:text-gray-400 mt-1">
          {isOverLimit ? '超出' : '剩余'} kcal
        </div>
      </div>
    </div>
  );
}
